require("config.options")
require("config.keymaps")
require("config.lazy")
require("custom.hb_easy_term.main")
require("custom.java_test_helper")
require("custom.hydras.locate_stuff")
require("custom.hydras.escape_on_term")
require("custom.hydras.space_to_enter")
